services:
  app:
    build:
      context: .
    ports:
      - 5910:5910
    environment:
      - RENDER_GROUP_GID=488 # replace with GID of the group which owns the /dev/dri/renderD128 device
      - SWAY_RESOLUTION=1920x1080
      - WAYVNC_PORT=5910
      - WAYVNC_ENABLE_AUTH=true
      - WAYVNC_USERNAME=wayvnc
      - WAYVNC_PASSWORD=wayvnc
    devices:
      - /dev/dri
    security_opt:
      - seccomp:unconfined
