[project]
name = "zendriver-docker-example"
version = "0.1.0"
description = "Example project for using Zendriver with Docker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "zendriver>=0.1.5",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.13.0",
    "ruff>=0.7.4",
]
